### ISSUE TITLE
Text to big and overflowing

### ISSUE THREAD

**Issue by bermanapps** [AhmedLSayed9/dropdown_button2#173] opened 2023-08-03 19:08 UTC
Hi,
Im using this library, but on some devices when the text is bigger, the writing doesnt all show up, and the widget doesnt expand to fill all the text.
Attached is a screen shot.
<img width="301" alt="Screenshot 2023-08-03 at 8 08 23 PM" src="https://github.com/AhmedLSayed9/dropdown_button2/assets/28511238/92164a18-f780-4a37-b43a-1d515e9bba07">
The full text is "This apointment is urgent", and the second option is "This apointment can wait a day or two". But as you see, its not showing the full text.
Here is my full code of the widget.

```
  DropdownButtonFormField2(
                decoration: InputDecoration(
                  isDense: true,
                  contentPadding: EdgeInsets.zero,
                  border: OutlineInputBorder(
                    borderSide: BorderSide(color: Colors.blue, width: 0.0),
                    borderRadius: BorderRadius.circular(15),
                  ),
                  // label: Text('Gender'),
                  //Add more decoration as you want here
                  //Add label If you want but add hint outside the decoration to be aligned in the button perfectly.
                ),
                isExpanded: true,
                hint: Text(
                  'Priority',
                  style: TextStyle(fontSize: 20),
                ),
                items: priorityDropDownList
                    .map((item) => DropdownMenuItem<String>(
                  value: item,
                  child: Text(
                    item,
                    style: TextStyle(
                      fontSize: 20,
                    ),
                  ),
                ))
                    .toList(),
                validator: (value) {
                  if (value == null) {
                    return 'Priority';
                  }
                  return null;
                },
                // value: selectedValue == 'NONE' ? null : selectedValue,
                onChanged: (value) {
                  //Do something when changing the item if you want.
                  // ref.read(intValueProvider.notifier).state = getIntFromStringValue(value!);
                  selectedPriority = value!;
                },
                onSaved: (value) {
                  // selectedValue = value.toString();
                },
                buttonStyleData: const ButtonStyleData(
                  height: 60,
                  padding: EdgeInsets.only(left: 0, right: 10),
                ),
                iconStyleData: const IconStyleData(
                  icon: Icon(
                    Icons.arrow_drop_down,
                    color: Colors.black45,
                  ),
                  iconSize: 30,
                ),
                dropdownStyleData: DropdownStyleData(
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(15),
                  ),
                ),
              ),

```

**Comment by AhmedLSayed9** [comment] 2023-08-03 19:11
Duplicate of https://github.com/AhmedLSayed9/dropdown_button2/issues/163

**Comment by AhmedLSayed9** [comment] 2023-08-03 19:12
Wait, are you referring to the height not the width?

**Comment by bermanapps** [comment] 2023-08-03 19:16
Height

**Comment by AhmedLSayed9** [comment] 2023-08-03 19:26
Set `isDense` to false and you can increase itemHeight using `menuItemStyleData.height`.

**Comment by bermanapps** [comment] 2023-08-03 20:24
So there is no way that the height will automatically adjust based on how many lines is needed for the text?

**Comment by AhmedLSayed9** [comment] 2023-08-04 02:27
> So there is no way that the height will automatically adjust based on how many lines is needed for the text?

Currently, no. That's because the menu height is being calculated based on items heights.
The only way to make this work is to make sure menu height is predefined instead. but that means menu height could have an empty space at the end too.

Anyway, this is relevant to [the open](https://github.com/AhmedLSayed9/dropdown_button2/issues/111) which demand a predefined menu height too.

**Closed** 2023-10-21 20:59 UTC
Labels: enhancement, guidance
