### ISSUE TITLE
Drop-Down opens very slowly after one of the last items has been selected in a large list (2500 entries)

### ISSUE THREAD

**Issue by wkolov** [AhmedLSayed9/dropdown_button2#218] opened 2023-11-16 10:02 UTC
You can reproduce it, if you simply replace the items list in your examples with this:
`  final List<String> items = List<String>.generate(2500, (i) => '$i. item');`

At the beginning, the list opens quickly, but it slows down as you go further down the entries you select. I assume it looks up for the selected item to mark it.

**Comment by wkolov** [comment] 2024-05-08 15:28
Are there any news regarding this issue? It's actually a serious problem since meanwhile we have up to 5000 entries in the drop-down list and customers complain loudly about miserable performance. It seams to be a bi issue in browsers (tested with Chrome and Safari). The performance in mobile apps is much better even with large lists.

**Comment by AhmedLSayed9** [comment] 2024-05-08 15:52
Sorry for the late response.
I'll check it this weekend and see if there's something we can do.

**Comment by AhmedLSayed9** [comment] 2024-05-14 21:22
@wkolov Do you experience a delay if the selected item is at the beginning of the list or only in case it's far from start?

I was able to re-produce it using flutter's `DropdownButton` too.

**Comment by wkolov** [comment] 2024-05-15 07:56
@AhmedLSayed9 This gets worse the further it gets from the beginning. DropdownButton is affected too, but it's not that slow (I measured 10 vs 17 seconds in my test setup). The issue is somewhat hard to catch. It seems to depend on the amount of free memory in the system and all the profiling tools I tried to use don't show anything helpful or even crash. I have found another searchable dropdown: https://pub.dev/packages/dropdown_search. It doesn't scroll to the selected item when the drop-down list opens and thus it is always quick.

**Comment by AhmedLSayed9** [comment] 2024-05-15 16:08
> @AhmedLSayed9 This gets worse the further it gets from the beginning. DropdownButton is affected too, but it's not that slow (I measured 10 vs 17 seconds in my test setup). The issue is somewhat hard to catch. It seems to depend on the amount of free memory in the system and all the profiling tools I tried to use don't show anything helpful or even crash. I have found another searchable dropdown: https://pub.dev/packages/dropdown_search. It doesn't scroll to the selected item when the drop-down list opens and thus it is always quick.

Well, the issue is scrolling over a very big list without specifying [itemExtent](https://api.flutter.dev/flutter/widgets/ListView/itemExtent.html) causes janky performance.
We need to somehow set `itemExtent`, I'll look into it.

**Comment by AhmedLSayed9** [comment] 2024-05-16 00:55
A fix is incoming. You'll be able to scroll fast even with different items length & separators:
https://github.com/AhmedLSayed9/dropdown_button2/assets/70890146/3fd5ffeb-af98-409d-872c-98e84623e9de

_Note:_ the min supported flutter version will be increased to `3.16.0` and you'll have to not use `intrinsicHeight: true` of DropdownItem "which is false by default".

**Closed** 2024-05-16 01:27 UTC
Labels: enhancement

**Comment by AhmedLSayed9** [comment] 2024-05-16 02:44
`3.0.0-beta.14` is released, give it a try :)

**Comment by wkolov** [comment] 2024-05-17 07:29
I have tried it and the performance looks very good now. Thanks.
