### ISSUE TITLE
Searching item.child not working on release mode but in debug mode run successfully.

### ISSUE THREAD

**Issue by irving-dp** [AhmedLSayed9/dropdown_button2#240] opened 2024-02-16 16:53 UTC
I've try so many times to fix this case searching item.child didn't work in release mode. because in item child it read as widget text then I add toString().toLowerCase() function. Please help solve this case, here is my code that I'm focused on

`searchMatchFn: (item, searchPasien) {
      return item.child.toString().toLowerCase().contains(searchPasien.toLowerCase());
},`

**Comment by AqsoLath** [comment] 2024-04-29 04:20
> I've try so many times to fix this case searching item.child didn't work in release mode. because in item child it read as widget text then I add toString().toLowerCase() function. Please help solve this case, here is my code that I'm focused on
> 
> `searchMatchFn: (item, searchPasien) { return item.child.toString().toLowerCase().contains(searchPasien.toLowerCase()); },`

Hi, I also get this exact bug, do you have any solution how to fix it? Any help would be appreciated, thanks in advance...

**Comment by heshesh2010** [comment] 2024-10-27 17:23
any update on this ?

**Comment by AhmedLSayed9** [comment] 2024-10-27 17:36
Can anyone provide a sample that reproduces this issue?

**Comment by heshesh2010** [comment] 2024-10-27 17:53
> Can anyone provide a sample that reproduces this issue?

please check your email

**Comment by AhmedLSayed9** [comment] 2024-10-27 18:10
This issue is because of `toString()` acts differently on debug/release modes. Might be related to https://github.com/flutter/flutter/issues/148983 or wherever `toString` is used from.

The unexpected behavior of `child.toString()` on debug/release modes is unrelated to this package, so I'll close this.

Feel free to share the model `child` If you need further help.

**Closed by AhmedLSayed9** 2024-10-27 18:10 UTC
Labels: question

**Comment by AhmedLSayed9** [comment] 2024-10-27 19:12
This issue is related to `equatable`

The `stringify` value defaults to true in debug mode and false in release mode.

You can fix it by overriding the global [stringify] setting:
```dart
EquatableConfig.stringify = true
```
or, override `stringify` for a particular class like `Speciality`:
```dart
  @override
  bool? get stringify => true;
```

I've opened an [issue](https://github.com/felangel/equatable/issues/181) there that suggests changing this behavior to act the same on debug/release modes.

**Comment by AhmedLSayed9** [comment] 2024-10-27 19:24
Furthermore, you might want to rely on `props` for a better search experience:
```dart
return item.props.any(
  (prop) => prop.toString().toLowerCase().contains(searchValue.toLowerCase()),
);
```
