### ISSUE TITLE
dropdownDecoration applied instead of buttonDecoration, when using Android Back Button

### ISSUE THREAD

**Issue by EskAere** [AhmedLSayed9/dropdown_button2#51] opened 2022-07-18 13:33 UTC
Hi, 

After closing a Dropdown using the Android back button, the dropdownDecoration is applied on the button instead of the buttonDecoration.

Closing the dropdown by pressing on the button or outside the dropdown is functional.

**Comment by AhmedLSayed9** [comment] 2022-07-18 13:55
I've tested it and buttonDecoration is applied on the button when using Android's back button.
Could you please share a sample example that produce this issue?

**Comment by EskAere** [comment] 2022-07-18 14:20
Hi, thanks you for your quick response. 

Here is a simplified version of my Dropdown Widget : 
`
class DropdownWidget extends StatefulWidget {
  final List<String> values;
  final String? value;
  final Function(String?)? onChanged;

  const DropdownWidget({
    Key? key,
    required this.values,
    required this.value,
    required this.onChanged,
  }) : super(key: key);

  @override
  State<DropdownWidget> createState() => _DropdownWidgetState();
}

class _DropdownWidgetState extends State<DropdownWidget> {
  bool _isDropdownOpen = false;

  @override
  Widget build(BuildContext context) {
    return DropdownButtonHideUnderline(
      child: DropdownButton2(
        isExpanded: true,
        value: widget.value,
        onChanged: widget.onChanged,
        onMenuStateChange: (isOpen) {
          setState(() {
            _isDropdownOpen = isOpen;
          });
        },

        //Items
        itemPadding: EdgeInsets.zero,
        items: widget.values.map((String type) {
          return DropdownMenuItem<String>(
            value: type,
            child: Text(type),
          );
        }).toList(),

        //Button
        buttonHeight: 50.0,
        buttonPadding: const EdgeInsets.symmetric(horizontal: 14),
        buttonDecoration: BoxDecoration(
          borderRadius: _isDropdownOpen
              ? BorderRadius.only(
                  topLeft: Radius.circular(10),
                  topRight: Radius.circular(10),
                )
              : BorderRadius.circular(10),
          color: AppColors.white,
        ),

        //Dropdown
        dropdownDecoration: BoxDecoration(
          borderRadius: BorderRadius.only(
            bottomLeft: Radius.circular(10),
            bottomRight: Radius.circular(10),
          ),
          color: AppColors.white,
        ),
        dropdownPadding: EdgeInsets.zero,
        dropdownElevation: 0,
        dropdownMaxHeight: 250,
        scrollbarAlwaysShow: true,
      ),
    );
  }
}

`

**Comment by AhmedLSayed9** [comment] 2022-07-18 16:20
https://user-images.githubusercontent.com/70890146/179555133-6b52fb69-ea39-42c8-9130-988429465742.mov


I've tried your sample code and couldn't reproduce the issue.
`onMenuStateChange` triggers when the dropdown menu route get removed whatever the way.

**Comment by EskAere** [comment] 2022-07-20 11:55
Indeed !
You made me try on an emulator and the issue is gone. 

However, even on an empty project (just like you), the issue persists on my physical Android device.
I'll leave it as is for now and investigate later, but I guess the issue is not related to your package. 

Thank you for your time <3 
I suppose the issue can be closed for now ? I'll reopen if needed

**Comment by AhmedLSayed9** [comment] 2022-07-20 12:05
I've never noticed this issue on my old physical Android device (using iPhone now). so, It might be related to your device.
You should try to test it on another device that might help finding if the issue related to some device?

Alright! I'll close this for now. Feel free to re-open if needed.

**Closed by AhmedLSayed9** 2022-07-20 12:05 UTC
