### ISSUE TITLE
Make the dropdown width depends on the max width of the menu item

### ISSUE THREAD

**Issue by anasboyka** [AhmedLSayed9/dropdown_button2#177] opened 2023-08-16 05:22 UTC
I have a dropdown button for page navigation.. however if the number is 2 digit or more, the dropdown wont show rest of the number.. I cant give a fixed width to the dropdown since the menu item widget can have different width..

### expected result

![Screenshot 2023-08-16 at 1 20 49 PM](https://github.com/AhmedLSayed9/dropdown_button2/assets/61081936/9d25473c-48fe-4184-86e8-5cbfc022c70a)

### actual result

![Screenshot 2023-08-16 at 1 14 25 PM](https://github.com/AhmedLSayed9/dropdown_button2/assets/61081936/500f7e49-0c39-4b02-90f2-ad258524548c)

**Comment by AhmedLSayed9** [comment] 2023-08-16 07:19
Duplicate of #163

**Closed by AhmedLSayed9** 2023-08-16 07:19 UTC
